#pragma once

// From glfw3.h
#define CAT_MOUSE_BUTTON_1      0
#define CAT_MOUSE_BUTTON_2      1
#define CAT_MOUSE_BUTTON_3      2
#define CAT_MOUSE_BUTTON_4      3
#define CAT_MOUSE_BUTTON_5      4
#define CAT_MOUSE_BUTTON_6      5
#define CAT_MOUSE_BUTTON_7      6
#define CAT_MOUSE_BUTTON_8      7
#define CAT_MOUSE_BUTTON_LAST   CAT_MOUSE_BUTTON_8
#define CAT_MOUSE_BUTTON_LEFT   CAT_MOUSE_BUTTON_1
#define CAT_MOUSE_BUTTON_RIGHT  CAT_MOUSE_BUTTON_2
#define CAT_MOUSE_BUTTON_MIDDLE CAT_MOUSE_BUTTON_3
